# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20171109_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/img/'),
        ),
    ]
